### ISSUE TITLE
[Fix] 채팅 서버 예외 및 에러 핸들링 구현

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#103]
# 기능 이슈

## Description

> 에러 핸들링 구현
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 에러 코드 정의 및 enum 클래스 구현
- [x] 예외 클래스 구현
- [x] 에러 응답 클래스 구현
- [x] 예외 발생 위치 및 핸들러 구현
<br>
