### ISSUE TITLE
[Feat] 채팅 서비스 채팅DB(MongoDB) 연결

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#11]
# Feat

## Description

> 채팅 서비스 DB 연결
<br>

## To-do

> Mongo DB 설정, 연결, 배포 
- [x] appliacation.yml MongoDB 설정
- [x] MongoDB Atlas 배포
- [x] Spring Boot MongoDB 연결
<br>
