### ISSUE TITLE
[Feat] 채팅 서버 - 상태관리 서버 gRPC 구현

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#113]
# 기능 이슈

## Description

> 채팅 서버, 상태관리 서버 간 통신을 gRPC로 재구성
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 상태관리 서버 gRPC 함수 구현
- [x] 채팅 서버 gRPC 함수 구현
- [x] protobuf 파일 구현 (chat.proto)
<br>

## 참고자료 및 기타

> 참고자료가 있다면 첨부해주세요
> 향 후 구현 예정
> 1) TCP VS gRPC 성능 평가
> 2) gRPC 예외처리
> 3) 네트워크 이용률 모니터링
<br>
