### ISSUE TITLE
[Setting] 스터디 방 관리 서비스 DB(MySQL) 연결 및 JPA 연동

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#15]
# Setting

## Description

> 스터디 방 관리 서비스 DB(MySQL ) 연결과 JPA 연동
<br>

## To-do

> 기능 개발 전 DB 및 개발 환경 Setting
- [x] 스터디 방 관리 서비스 Directory Setting
- [x] appliacation.yml MySQL랑 JPA 설정
- [x]  build.gradle 수정
<br>
