### ISSUE TITLE
[Feat] JPA Entity 생성 및 공개 스터디방 생성 기능 개발

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#16]
# Feat

## Description

> 공개 스터디방을 생성해서 DB에 저장 될 수 있도록 JPA Entity를 생성하고 공개 스터디방 생성 기능을 개발 

<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 공개 스터디 방 관련 JPA Entity 개발
- [x] 스터디 방 생성 기능 관련 Controller, Service, Repository 개발
- [x] 스터디 방 생성 API의 Request, Response 개발
<br>
