### ISSUE TITLE
[Feat] 스터디 방 관리 서버 Exception Handler 개발

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#18]
# Feat

## Description

> 스터디 방 관리 서버에서 Exception을 던졌을 때 받아서 처리해줄 Exception Handler 개발 
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 발생할 Exception 관련 status. errorCode, description을 정의해둘 ErrorCode enum class 개발
- [x] Exception 발생시 throw 하기위한 ApplicationException 개발
- [x] throw된 모든 Exception을 받아서 처리 해줄 GlobalControllerAdvice 개발
<br>
