### ISSUE TITLE
[Feat] 채팅 내역 가져오기 

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#23]
# Feat

## Description

> 스터디 그룹의 채팅 내역 가져오기
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] MongoDB에 스터디 그룹별 채팅 어떻게 관리하는 지 조사
- [x] 스터디 그룹별 채팅 내역 가져오기
- [x] 채팅 내역 페이지네이션
- [x] 채팅 저장 및 쿼리 테스트
<br>

## 참고자료 및 기타

> room 컬렉션, message 컬렉션 분리 VS room 객체 내부에 message를 배열로 구현
https://stackoverflow.com/questions/11228351/mongodb-structure-for-message-app

<br>
