### ISSUE TITLE
[Feat] 경고, 강퇴, 방장위임 기능 구현

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#33]
# Feat

## Description

> 스터디방에서 방장만 경고, 강퇴, 방장위임 할수있도록 기능 구현
<br>

## To-do

- [x] 경고 기능 구현
- [x] 강퇴 기능 구현
- [x] 방장위임 기능 구현
<br>
