### ISSUE TITLE
[Feat] 스터디 그룹 관련 기능 구현

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#35]
# Feat

## Description

> 스터디 그룹에 필요한 모든 기능 구현
<br>

## To-do

- [x] 스터디 그룹 생성, 수정, 공지사항 설정 기능 구현
- [x] 스터디 그룹의 roomCode 생성과 가입, 삭제/탈퇴, 입장 기능 구현
- [x] 스터디 그룹의 경고, 강퇴, 방장위임 기능 구현
