### ISSUE TITLE
[Feat] 웹 소켓을 활용한 접속 상태 구현 

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#37]
# Feat

## Description

> 웹 소켓을 활용한 접속 상태 구현 
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [ ] 웹 소켓 세션 저장
- [ ] 웹 소켓 연결/해제 구현
- [ ] TCP Client/Server 구현
- [ ] 웹 소켓 연결/해제 시 해당 정보를 상태관리 서버에 TCP 정보 보냄
- [ ] TCP Server 소켓 세션 저장 구현
<br>

## 참고자료 및 기타

> [WebSocket Handler](https://zara49.tistory.com/226)
> [TCP Client](https://developer0513.tistory.com/245?category=806731)
<br>
