### ISSUE TITLE
[Feat] Blob(이미지, 비디오, 파일) 채팅 전송

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#51]
# Feat

## Description

> Blob 채팅 전송
<br>

## To-do

- [x] AWS S3 생성 및 프로젝트에 설정
- [x] Blob 채팅 전달 시 AWS S3에 업로드
- [x] Blob URI값 채팅방에 전달
<br>

## 참고자료 및 기타

> [Socket blob 전송 방법 - Stack Overflow](https://stackoverflow.com/questions/31111528/sending-images-files-over-sockjs-spring-websocket-stomp)
<br>
