### ISSUE TITLE
[Feat] 상태관리서버 - Signaling 서버에서 전달받은 실시간 정보 저장

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#61]
# 기능 이슈

## Description

> Signaling 서버에서 전달받은 실시간 정보 저장
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [ ] 실시간 정보 데이터 구조 디자인
- [ ] 전달 받는 방식에서 어디 서버에서 왔는 지를 확인하도록 반영
- [ ] Redis에 JSON 저장하도록 구현
<br>
