### ISSUE TITLE
[Feat] 시그널링 서버 Timer 기능 추가

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#67]
# 기능 이슈

## Description

> 같은 방에 존재하는 유저들끼리 공부시간을 공유하기 위한 Timer 기능 추가
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 새로운 유저가 방에 입장했을 때, 기존 유저들과 새 유저간의 타이머 상태, 공부시간 공유
- [x] 유저가 timer를 시작하거나 멈췄을 때, 모든 유저들에게 timerStateAnswer을 보내도록 구현 
- [x] 방 나갈때 timer 저장 기능 구현
<br>
