### ISSUE TITLE
[Feat] 상태관리서버 - 유저 공부 시간 정보 알림

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#77]
# 기능 이슈

## Description

> 유저 서버에서 공부시간 요청 시 사용자의 공부 시간 알림.
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [ ] 유저 서버로부터 TCP 요청 받는 부분 구현
- [ ] TCP 응답 구현
- [ ] userId가 배열로 올 경우도 고려하여 구현
<br>
