### ISSUE TITLE
[Fix] 채팅서버 - 접속 상태 관리 로직 수정

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#84]
# 기능 이슈

## Description

> 접속 상태 관리 로직 수정
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 채팅서버 - CONNECT  , SUBSCRIBE할 떄 DISCONNECT 가 바로 호출 되는 문제 해결
- [x] 채팅서버 - CONNECT는 로직에서 삭제
- [x] 채팅서버 - SUBSCRIBE : 접속, DISCONNECT 또는 UNSUBSCRIBE : 접속 해제
- [x] 채팅서버 - 접속 해제 시에는 roomId 는 "" 로 보냄.
- [x] 상태관리서버 - 채팅 서버 변경 사항에 따라 로직 수정
<br>
