### ISSUE TITLE
[Fix] 실시간 정보 Redis 로직 수정

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#91]
## Description

> 상태관리 서버의 실시간 정보 Redis 로직 수정
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] redis 조회 시 데이터가 없으면 비어있는 객체에 null 값들을 필드들에 담아 응답.
- [x] Json 변환 Bean  활용
- [x] 유저서버에 복수 ID 요청 -> 단일 ID로 요청 
- [x] RedisService 함수명 정리
- [x] MessageService 코드 정리
<br>
