### ISSUE TITLE
[Test] 상태관리서버 <-> 시그널링 서버, 방관리 서버, 유저 서버 TCP 통신 테스트

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#92]
# 기능 이슈

## Description

> TCP 통신 테스트
<br>

## To-do

- [x]  시그널링 서버 <-> 상태관리 서버, 공부 시간 조회 및 저장
- [x]  상태관리 서버 -> 방관리 서버, 방 Out 알림
- [x]  유저 서버 <-> 상태관리 서버, 사용자의 공부 시간 조회
<br>
