### ISSUE TITLE
[Feat] 룸서버 - 경고 ,강퇴, 방장위임시 TCP 보내기

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#94]
# 기능 이슈

## Description

> 클라이언트가 경고, 강퇴, 방장위임 API 호출시, 상태관리서버로 관련해서 TCP 데이터를 보내줍니다.
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [ ] 상태관리 서버로 TCP를 보내기 위한 TCPClient 설정
- [ ] 경고, 강퇴, 방장위임 api 호출시 , 상태관리서버로 TCP 보내기 구현
- [ ] 상태관리서버로부터 roomOut TCP 요청을 받았을 때, 유저가 방장인지 아닌지에 대한 응답 구현 
<br>
