### ISSUE TITLE
[Feat] 경고, 강제퇴장, 경고 누적 퇴장, 방장 위임 기능 구현

### ISSUE THREAD

**Issue by jhl8109** [jaehanbyun/SGS-BE#96]
# 기능 이슈

## Description

> 룸서버 -> 상태관리서버 -> 시그널링 서버 관련 기능 추가 : 경고, 강제 퇴장, 경고 누적 퇴장, 방장 위임
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 상태관리 서버 TCP 명세에 추가 사항 기록
- [x] 상태관리 서버가 룸서버에서 통신 수신하는 부분 구현
- [x] 상태관리 서버가 시그널링으로 통신 송신하는 부분 구현
<br>

## 참고자료 및 기타

> 참고자료가 있다면 첨부해주세요
<img width="300" alt="스크린샷 2023-06-09 오후 4 05 09" src="https://github.com/jaehanbyun/SGS-BE/assets/78259314/5fcf995d-2946-474d-9bdd-e18fd422dac0">
<img width="1385" alt="스크린샷 2023-06-09 오후 4 06 13" src="https://github.com/jaehanbyun/SGS-BE/assets/78259314/a1af04a3-333b-4534-bf8f-9264fc3accb9">

<br>
