### ISSUE TITLE
[Feat] 룸서버 - 방장이 나갔을 때, 방 폭파 대신 방장 위임으로 수정

### ISSUE THREAD

**Issue by kimdonwoo** [jaehanbyun/SGS-BE#98]
# 기능 이슈

## Description

> 유저가 나가서 roomOut TCP 요청을 상태관리서버로부터 받으면, 유저가 방장인지 아닌지에 따라 구분하여 응답해줍니다. 방장이 방을 나가면 방폭파시키는 것 대신, 남아 있는 유저중 가장 먼저 들어온 유저를 골라 방장위임을 하는 식으로 수정하였습니다.
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 일반 유저 또는 방장이 방을 나가서 상태관리서버로 부터 TCP 요청이오면 방인원 수 감소하고 방 인원이 0명이면 방을 삭제하도록 구현
- [x] 일반 유저 나가면 해당 userRoom에 leftAt에 기록
- [x] 방장이 나가면 현재 방에 남아있는 유저중에 accessAt이 가장 빠른 유저로 방장을 위임하고 상태관리서버로 응답을 보내줌
<br>
